# Generated by Django 4.2.5 on 2023-11-06 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_alter_book_viewed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedBooks',
        ),
    ]
