# Generated by Django 4.2.5 on 2023-11-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_viewedbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedBooks',
        ),
    ]
