# Generated by Django 4.2.5 on 2023-11-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_viewedbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='viewed_by',
        ),
    ]
