# Generated by Django 4.2.5 on 2023-11-06 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_remove_book_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
