# Generated by Django 4.2.5 on 2023-11-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_viewed_by'),
        ('catalog', '0010_auto_20231106_1639'),
    ]

    operations = [
    ]
