# Generated by Django 4.2.5 on 2023-11-09 18:12

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rating_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.book_directory_path),
        ),
    ]
