# Generated by Django 4.2.5 on 2023-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_book_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
