# Generated by Django 4.2.5 on 2023-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_book_total_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_income',
        ),
        migrations.AlterField(
            model_name='book',
            name='fandoms',
            field=models.ManyToManyField(blank=True, to='catalog.fandom'),
        ),
    ]
