# Generated by Django 4.2.5 on 2023-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_book_total_income_alter_book_fandoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fandoms',
            field=models.ManyToManyField(to='catalog.fandom'),
        ),
    ]
