# Generated by Django 4.2.5 on 2023-11-27 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0024_alter_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_views',
        ),
        migrations.CreateModel(
            name='ViewedChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateField(auto_now_add=True, verbose_name='Дата перегляду')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_views',
            field=models.ManyToManyField(blank=True, related_name='viewed_chapters', through='catalog.ViewedChapters', to=settings.AUTH_USER_MODEL),
        ),
    ]
